### ISSUE TITLE
k8s external ip configuration

### ISSUE THREAD

**Issue by quasiben** [jcrist/dask-gateway#68]
@jacobtomlinson made a comment [here](https://github.com/jcrist/dask-gateway/pull/59#pullrequestreview-266742868) on externalizing services.  I would suggest that the default be a `NodePort` for a two reasons:

- Ingress/LoadBalancers can be tricky to setup/configure -- especially for beginners
  - note: on clouds (GKE at least) ingress is automatically setup
- Testing may be challenging (though not impossible)

NodePorts are builtin to k8s, we can easily test, and the setup should *work out of the box* without additional configuration

When using a NodePort I believe the pod/service is accessible by any nodeIP:
https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-type-nodeport

For configuring a NodePort I would recommend looking at:
https://kubernetes.io/docs/tasks/access-application-cluster/service-access-application-cluster/

or the following:

```
kind: Service 
apiVersion: v1 
metadata:
  name: SERVICENAME
spec:
  type: NodePort
  selector:
    app: APPNAME
  ports:
    # nodePort - a static port assigned on each the node
    # port - port exposed internally in the cluster (assigned on creation)
    # targetPort - the container port to send requests to
    - nodePort: 30163
      port: 8080 
```

cc @jcrist 

@jacobtomlinson do you have thoughts here ?
